repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.10.1
    
    hooks:
      - id: golangci-lint-fmt
        entry: cd stash-backend && golangci-lint fmt
      - id: golangci-lint-full
        entry: cd stash-backend && golangci-lint run --fix
